export const types = {
    // Sync
    FETCH_TODOS:      "FETCH_TODOS",
    CREATE_TODO:      'CREATE_TODO',
    UPDATE_TODO:      'UPDATE_TODO',
    UPDATE_TODOS:     'UPDATE_TODOS',
    UPDATE_ALL_TODOS: 'UPDATE_ALL_TODOS',
    REMOVE_TODO:      'REMOVE_TODO',

    // Async
    FETCH_TODOS_ASYNC: "FETCH_TODOS_ASYNC",
    CREATE_TODO_ASYNC: 'CREATE_TODO_ASYNC',
    UPDATE_TODO_ASYNC: 'UPDATE_TODO_ASYNC',
    REMOVE_TODO_ASYNC: 'REMOVE_TODO_ASYNC',
};
